# Generated by Django 5.2.7 on 2025-10-02 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_colaborador_alter_setor_nome_setor_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto'),
        ),
    ]
