# Generated by Django 5.2.7 on 2025-10-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_alter_protocolo_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='item_nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
